import process from 'node:process';globalThis._importMeta_={url:import.meta.url,env:process.env};export { h as default } from './chunks/nitro/nitro.mjs';
import 'node:http';
import 'node:https';
import 'node:events';
import 'node:buffer';
import 'vinxi/lib/invariant';
import 'vinxi/lib/path';
import 'node:url';
import 'node:async_hooks';
import 'react/jsx-runtime';
import '@tanstack/react-router';
import '@tanstack/react-router-devtools';
import 'node:stream';
import 'react-dom/server';
import 'node:stream/web';
import 'node:fs';
import 'node:path';
import 'node:crypto';
//# sourceMappingURL=main.mjs.map
